---
apiVersion: v1
kind: Namespace
metadata:
  name: gitlab
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: gitlab
  namespace: gitlab
spec:
  interval: 10m0s
  url: https://charts.gitlab.io/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitlab
  namespace: gitlab
spec:
  chart:
    spec:
      chart: gitlab
      sourceRef:
        kind: HelmRepository
        name: gitlab
  values:
    global:
      hosts:
        domain: "gitlab.mael.me"
    certmanager-issuer:
      email: "maelacademy@gmail.com"
  interval: 1m0s
